### ISSUE TITLE
Trackma fails to launch on start

### ISSUE THREAD

**Issue by ironcrown9** [z411/trackma#115]
Been a few months since I used it. Spun it up, crashes on startup with this error:

    Initializing engine...
    Engine: Trackma v0.3 - using account ironcrown9(mal).
    Engine: Reading config files...
    Data: Initializing...
    libmal: Initializing...
    Data: Using libmal (anime)
    libmal: Logging in...
    libmal: Downloading list...
    Traceback (most recent call last):
       File "/usr/bin/trackma", line 9, in <module>
       load_entry_point('Trackma==0.3', 'console_scripts', 'trackma')()
     File "/usr/lib/python2.7/site-packages/trackma/ui/cli.py", line 679, in main
      main_cmd.start()
    File "/usr/lib/python2.7/site-packages/trackma/ui/cli.py", line 108, in start
     self.engine.start()
    File "/usr/lib/python2.7/site-packages/trackma/engine.py", line 176, in start
      (self.api_info, self.mediainfo) = self.data_handler.start()
    File "/usr/lib/python2.7/site-packages/trackma/data.py", line 150, in start
      self.download_data()
    File "/usr/lib/python2.7/site-packages/trackma/data.py", line 474, in download_data
      self.showlist = self.api.fetch_list()
    File "/usr/lib/python2.7/site-packages/trackma/lib/libmal.py", line 146, in fetch_list
       root = ET.ElementTree().parse(data, parser=self._make_parser())
    File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
       parser.feed(data)
    File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
      self._raiseerror(v)
    File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
      raise err
       xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5, column 166

Not a config issue since I start get the same error if I scrap my dotfiles.

**Comment by z411** [comment]
I think it's because MAL API was having problems today; please check if it's still happening as it works for me now.

**Comment by ironcrown9** [comment]
Yep, it seems to be working now. Sorry to clutter the issue tracker, should've waited a bit longer.

**Comment by z411** [comment]
No problem.
