### ISSUE TITLE
Error when selecting a show

### ISSUE THREAD

**Issue by Fredo-p** [z411/trackma#121]
When opening trackma-gtk, and choose Humminbird account, selecting a show would display the image. After a few min, the following error displays and the image stops loading:

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/Trackma-0.3-py2.7.egg/trackma/ui/gtkui.py", line 1007, in run
    img_file = StringIO(urllib2.urlopen(req).read())
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

![error chain](https://cloud.githubusercontent.com/assets/5199706/8143390/bd3a716e-115d-11e5-8476-2432a1f2f92d.jpg)

Images do display on MAL account.

Lubuntu 14.04.2 LTS
-Version-
Kernel		: Linux 3.13.0-54-generic (i686)
Compiled		: #91-Ubuntu SMP Tue May 26 19:15:38 UTC 2015
C Library		: Unknown
Default C Compiler		: Unknown
Distribution		: Ubuntu 14.04.2 LTS	
Desktop Environment		: LXDE (Lubuntu)

Python 2.7.6 (default, Mar 22 2014, 22:59:38)

**Comment by z411** [comment]
Hi, I can't seem to reproduce the problem.
What's your distribution and the version of your Python install? (run the command python --version)

**Comment by z411** [comment]
This is pretty old but as we've identified in #249 it might have to do with your OpenSSL setup. If it persists please comment here and I'll re-open the issue.
