### ISSUE TITLE
[GTK] Search windows doesn't appear

### ISSUE THREAD

**Issue by zJoul** [z411/trackma#169]
Using the last commit (z411/trackma@43d54633111a2f0d1660630de549290740640fe5), when I select « Add/Search Shows », nothing happen.

The traceback is here :
```
~ » trackma-gtk 
Data: Locking database...
Data: Reading metadata...
Data: Reading queue...
Data: Reading info DB...
Data: No items in queue.
libmal: Logging in...
Data: Saving userconfig...
libmal: Downloading list...
libmal: Parsing anime list...
Data: Saving cache...
Data: Saving metadata...
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: Using inotify.
Tracker: inotify: Watching /home/yui/Videos
Tracker: inotify: Watching /home/yui/Videos/Ore Monogatari!!
Tracker: inotify: Watching /home/yui/Videos/ef a tale of memories
Tracker: inotify: Watching /home/yui/Videos/Yuriyuri San Hai
Tracker: inotify: Watching /home/yui/Videos/ef - a tale of melodies
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trackma/ui/gtkui.py", line 599, in do_addsearch
    win = ShowSearch(self.engine)
  File "/usr/lib/python2.7/site-packages/trackma/ui/gtkui.py", line 2223, in __init__
    self.showlist = ShowSearchView(self.config['colors'])
AttributeError: 'ShowSearch' object has no attribute 'config'
Engine: Unloading...
Data: Unloading...
Data: No items in queue.
Data: Saving metadata...
```

I'm using Arch Linux, compiled with the AUR package

**Comment by Birdulon** [comment]
My bad, thanks for finding this.

**Comment by z411** [comment]
Bugfix merged, it should fix it. Thanks @Birdulon.

**Comment by zJoul** [comment]
I confirm, the bug it's fixed.
You can close it.

**Comment by ToostInc** [comment]
PKGBUILD is also updated now, thanks for the heads up
