### ISSUE TITLE
Remove traceback when timeout

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#194]
I have an error of timeout.

The traceback is very ugly to see:

```
libhb: Downloading list...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/gtkui.py", line 812, in task_sync
    self.engine.list_download()
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/engine.py", line 795, in list_download
    self.data_handler.download_data()
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/data.py", line 522, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/lib/libhb.py", line 112, in fetch_list
    shows = json.load(data)
  File "/usr/lib/python2.7/json/__init__.py", line 287, in load
    return loads(fp.read(),
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
timeout: timed out
```

Can you improve that and show a dialog window with an error of timeout?

**Comment by Birdulon** [comment]
+1

I've had the UI hang in a disabled state a few times when my internet connection is dropping out or heavily congested. There's a few networked calls that could use some exception handling, I'll have to take note next time I encounter hangups.

**Comment by z411** [comment]
libmal already handles this by having a timeout, but the rest of the libs don't.
Indeed we should be handling these and raising them as APIError.

**Comment by Birdulon** [comment]
I just noticed that a timeout on update results in the tracker stopping for me with the following:
`Tracker: Watch directory not found! Tracker will stop.`

For what it's worth, I'm using inotify and my library is on a folder that is mounted with sshfs. I don't think the directory drops out or anything, as I'm usually watching things from it with no interruption at the time and the tracker only stops if it fails to make an update.

**Comment by z411** [comment]
Tracker is now handling exceptions so this should be fixed.
