### ISSUE TITLE
Application crashes upon closing the Qt settings dialog

### ISSUE THREAD

**Issue by veluria** [z411/trackma#201]
With pyqt5: 

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/qtui.py", line 2010, in s_save
        self._save()
      File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/qtui.py", line 2000, in _save
        self.config['episodebar_style'] = self.ep_bar_style.itemData(self.ep_bar_style.currentIndex()).toInt()[0]
    AttributeError: 'int' object has no attribute 'toInt'
    [1]    6311 abort (core dumped)  trackma-qt

**Comment by Birdulon** [comment]
That toInt call was removed in 6253a4aa and I can't find the call in the
current master (5531f91cd). Which version are you running?

**Comment by veluria** [comment]
It was indeed an old version I had somehow installed. Thanks and sorry!
