### ISSUE TITLE
Rare crash on curses interface

### ISSUE THREAD

**Issue by rr-** [z411/trackma#261]
Steps to reproduce:

1. Start curses interface
2. Delete everything in the list (hammering <kbd>d</kbd> and <kbd>y</kbd>)
3. Repeat step 2. even after removing everything
4. Trackma asks "are you sure?" question even though nothing is selected anymore
5. Hitting yes causes exception

**Comment by rr-** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/trackma-curses", line 11, in <module>
    load_entry_point('Trackma==0.6.2', 'console_scripts', 'trackma-curses')()
  File "/usr/lib/python3.5/site-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/curses.py", line 1058, in main
    Trackma_urwid()
  File "/usr/lib/python3.5/site-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/curses.py", line 112, in __init__
    self.mainloop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/curses.py", line 1054, in keypress
    urwid.emit_signal(self, 'done', key.lower())
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/curses.py", line 476, in delete_request
    showid = self._get_selected_item().showid
AttributeError: 'NoneType' object has no attribute 'showid'
```
