### ISSUE TITLE
pyinotify tracker fails when video starts in kodi

### ISSUE THREAD

**Issue by Apewall** [z411/trackma#273]
Using kodi v16 & v17 on Ubuntu 16.04

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.6.2-py3.5.egg/trackma/tracker/pyinotify.py", line 132, in observe
    notifier.read_events()
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1239, in read_events
    uname = bname.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 10: invalid start byte
```

**Comment by z411** [comment]
Sorry for the late response. Could you tell me if this happens with any other player? What's the player regex you're using (`tracker_process` in config.json)? What's your system locale (You can run `echo $LANG` in the terminal)?

**Comment by Apewall** [comment]
Sorry for the same, I just rebuilt this system in Archlinux and am still hitting the same issue.

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/trackma/tracker/pyinotify.py", line 132, in observe
    notifier.read_events()
  File "/usr/lib/python3.6/site-packages/pyinotify.py", line 1239, in read_events
    uname = bname.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 10: invalid start byte

Traceback (most recent call last):
  File "/usr/bin/trackma", line 11, in <module>
    load_entry_point('Trackma==0.7', 'console_scripts', 'trackma')()
  File "/usr/lib/python3.6/site-packages/trackma/ui/cli.py", line 999, in main
    main_cmd.cmdloop()
  File "/usr/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)

$ echo $LANG
en_US.UTF-8

**Comment by z411** [comment]
I can't seem to reproduce as it works fine with my setup. Could you check if this still happens?
And if it does, does it happen with every file? If not, what filename?

**Comment by Apewall** [comment]
Updated to the lastest git version 0.7.3.r1.g5e27659-1 and the issue is no longer present.

pyinotify now detects the playing episode properly.
