### ISSUE TITLE
"Tracker has stopped."

### ISSUE THREAD

**Issue by Am4d** [z411/trackma#278]
Odd things seem to be happening specifically when watching "Little Witch Academia" and nothing else.
The tracker either crashes, says its "Not the latest episode" or just makes no attempt to update
`Tracker (pyinotify): Will update Little Witch Academia 2 in 30 seconds
Tracker (pyinotify): Tracker has stopped.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/trackma/tracker/pyinotify.py", line 139, in observe
    self.update_show_if_needed(self.last_state, self.last_show_tuple)
  File "/usr/lib/python3.6/site-packages/trackma/tracker/tracker.py", line 137, in update_show_if_needed
    self._update_show(state, show_tuple)
  File "/usr/lib/python3.6/site-packages/trackma/tracker/tracker.py", line 122, in _update_show
    action()
  File "/usr/lib/python3.6/site-packages/trackma/tracker/tracker.py", line 114, in <lambda>
    action = lambda: self._emit_signal('update', show['id'], episode)
  File "/usr/lib/python3.6/site-packages/trackma/tracker/tracker.py", line 100, in _emit_signal
    self.signals[signal](*args)
  File "/usr/lib/python3.6/site-packages/trackma/engine.py", line 155, in _tracker_update
    self.set_episode(show['id'], episode)
  File "/usr/lib/python3.6/site-packages/trackma/engine.py", line 447, in set_episode
    raise utils.EngineError('Episode out of limits.')
trackma.utils.EngineError: Episode out of limits.`

**Comment by Phidica** [comment]
I can verify this has been happening to me too, again only with Little Witch Academia. It may tie in to the somewhat unusual situation with that anime where it has an OVA of the same name from several years ago, thus the show is generally distinguished as "Little Witch Academia (TV)". I haven't been able to reliably demonstrate how this is causing a problem, however

**Comment by z411** [comment]
@Phidica Sounds like a very plausible explanation. Will look into it; it shouldn't cause a crash either way so I think we're hit 2 bugs here.

@Am4d Were you by any chance playing episode 2?

**Comment by Am4d** [comment]
@z411 Yeah, now I look at it episode two tries to update and crashes the tracker, all the other episodes just say "Player is not playing the next episode of Little Witch Academia. Ignoring."

I was having a similar problem with "Berserk (2016)" too, playing it from Trackma, it would say "Found player but show not in list.". Setting an alternate title of just "Berserk" seems to have fixed it.
Obviously another issue with multiple entries with the same name.

**Comment by z411** [comment]
Latest commit should fix the crash. The problem about it recognizing it as the OVA still remains, though.
