### ISSUE TITLE
Incorrect credentials

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#290]
```
Data: Can't process 3-gatsu no Lion, will leave unsynced.
Data: Info: Incorrect credentials.
Data: Saving cache...
Data: Saving queue...
Data: Saving queue...
Data: Cleared queue.
libkitsu: Refreshing access token...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/lib/libkitsu.py", line 165, in _request
    response = self.opener.open(request)
  File "/usr/lib64/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib64/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/ui/gtkui.py", line 829, in task_sync
    self.engine.list_download()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/engine.py", line 950, in list_download
    self.data_handler.download_data()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/data.py", line 532, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/lib/libkitsu.py", line 262, in fetch_list
    self.check_credentials()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/lib/libkitsu.py", line 253, in check_credentials
    self._request_access_token(True)
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/lib/libkitsu.py", line 216, in _request_access_token
    response = self._request('POST', self.url + '/oauth/token', post=params)
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.3-py3.5.egg/trackma/lib/libkitsu.py", line 175, in _request
    raise utils.APIError("Incorrect credentials.")
trackma.utils.APIError: Incorrect credentials.
```
But I connect to retrieve my list 1 hour ago, without reconnexion...

**Comment by Kcchouette** [comment]
Ok, I restart it, here the real issue, I think:

```
$ trackma-gtk

Data: Locking database...
Data: Reading metadata...
Data: Reading queue...
Data: Reading info DB...
Data: No items in queue.
Data: No items in queue.
libkitsu: Refreshing access token...
Data: Couldn't download list! Using cache.
Data: Reading cache...
```

**Comment by z411** [comment]
It seems there's a problem with the refresh token. Could you rename the file ~/.trackma/<user>.kitsu/user.json and see if the problem persists?

**Comment by Kcchouette** [comment]
renaming  ~/.trackma/.kitsu/user.json → the problem persists.

I've delete the .kitsu folder and restart trackma, and all was ok.
Thanks
