### ISSUE TITLE
Kitsu problem: index out of range at libkitsu.py:237

### ISSUE THREAD

**Issue by p-hash** [z411/trackma#295]
Every time I try to open my Kitsu account, i get this error:
```
Engine: Trackma v0.7.3 - using account [USERNAME](kitsu).
Engine: Reading config files...
Data: Initializing...
libkitsu: Initializing...
Data: Using libkitsu (anime)
libkitsu: Requesting access token...
libkitsu: Refreshing user details...
Traceback (most recent call last):
  File "/usr/bin/trackma", line 11, in <module>
    load_entry_point('Trackma==0.7.3', 'console_scripts', 'trackma')()
  File "/usr/lib/python3.6/site-packages/trackma/ui/cli.py", line 998, in main
    main_cmd.start()
  File "/usr/lib/python3.6/site-packages/trackma/ui/cli.py", line 158, in start
    self.engine.start()
  File "/usr/lib/python3.6/site-packages/trackma/engine.py", line 236, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib/python3.6/site-packages/trackma/data.py", line 173, in start
    self.download_data()
  File "/usr/lib/python3.6/site-packages/trackma/data.py", line 532, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python3.6/site-packages/trackma/lib/libkitsu.py", line 262, in fetch_list
    self.check_credentials()
  File "/usr/lib/python3.6/site-packages/trackma/lib/libkitsu.py", line 251, in check_credentials
    self._request_access_token(False)
  File "/usr/lib/python3.6/site-packages/trackma/lib/libkitsu.py", line 227, in _request_access_token
    self._refresh_user_info()
  File "/usr/lib/python3.6/site-packages/trackma/lib/libkitsu.py", line 237, in _refresh_user_info
    user = json_data['data'][0]
IndexError: list index out of range
```

**Comment by z411** [comment]
Does this still happen if you delete the `~/.trackma/<user>.kitsu` directory?

**Comment by p-hash** [comment]
Yes, problem remains same

**Comment by z411** [comment]
It seems there's an issue getting your user ID. Could you give me your username?

**Comment by p-hash** [comment]
Sure, i am `phash` on kitsu, but in trackma email is used as username

**Comment by z411** [comment]
You should use your username when adding your account, not your email.

**Comment by z411** [comment]
It seems the token authentication does accept the email as the username, that's why it doesn't throw an error, but it fails unexpectedly when attempting to retrieve your user ID from your username, that's why it crashes. Will fix that.

**Comment by p-hash** [comment]
When using username instead of email, everything works fine. Thank you.

**Comment by z411** [comment]
Fixed; using your e-mail should also work now.
