### ISSUE TITLE
Can't refresh kitsu list

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#304]
here is the traceback I have:
```
libkitsu: Downloading list...
libkitsu: Getting page 1...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib64/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib64/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/lib/libkitsu.py", line 165, in _request
    response = self.opener.open(request)
  File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/ui/gtkui.py", line 850, in task_sync
    self.engine.list_download()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/engine.py", line 961, in list_download
    self.data_handler.download_data()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/data.py", line 532, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/lib/libkitsu.py", line 286, in fetch_list
    data = self._request('GET', url)
  File "/usr/lib/python3.5/site-packages/Trackma-0.7.4-py3.5.egg/trackma/lib/libkitsu.py", line 183, in _request
    raise utils.APIError("URL error: %s" % e)
trackma.utils.APIError: URL error: <urlopen error [Errno -2] Name or service not known>
```

**Comment by z411** [comment]
Might this be a connection problem? Can you connect to Kitsu.io just fine?

**Comment by Kcchouette** [comment]
Ok it was a temporary problem.
