### ISSUE TITLE
pkg_resources.UnknownExtra: Trackma 0.7.4 has no such extra feature 'qt'

### ISSUE THREAD

**Issue by Hairo** [z411/trackma#306]
Getting this error when trying to run `trackma-qt` or `trackma-qt4`:

```
[hairo@hairo-casa ~]$ trackma-qt
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2576, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'qt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/trackma-qt", line 11, in <module>
    load_entry_point('Trackma==0.7.4', 'gui_scripts', 'trackma-qt')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2304, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2326, in require
    reqs = self.dist.requires(self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2579, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: Trackma 0.7.4 has no such extra feature 'qt'
```

Seems like a packaging error, i tried to fix it but i'm not familiar with python's packaging system.
Running manjaro with py3.6.2

**Comment by MadeOfMagicAndWires** [comment]
Are other ui's like gtk still working?

Also can you please paste the contents of `/usr/lib/python3.6/site-packages/Trackma-0.7.4-py3.6.egg-info/` somewhere? Particularly `entry_points.txt` and `requires.txt`.

**Comment by Hairo** [comment]
Yes, `trackma-gtk` works.

entry_points.txt
```
[console_scripts]
trackma = trackma.ui.cli:main
trackma-curses = trackma.ui.curses:main [curses]

[gui_scripts]
trackma-gtk = trackma.ui.gtkui:main [gtk]
trackma-qt = trackma.ui.qtui:main [qt]
trackma-qt4 = trackma.ui.qt4ui:main [qt]
```

requires.txt
```
[GTK]
pygobject

[curses]
urwid
```

Installed from a `git clone` with `python setup.py install`

**Comment by Hairo** [comment]
Removing all traces of it (old installation files) and reinstalling again fixed it.
