### ISSUE TITLE
Using symbols in Plex password

### ISSUE THREAD

**Issue by lucidnuance** [z411/trackma#316]
It seem that when using a password to authenticate to Plex which has symbols causes trackma to crash when trying to retrieve a Plex token. Changing my password to alphanumeric works just fine but character such as ?;>@%$^ do not work

**Comment by Hairo** [comment]
Interesting, the password i was using during testing had symbols and it didn't have any issue with it, i'll look into it soon.

Can you launch trackma from a console/terminal and post what pops up it crashes? (remove/censor any sensible information that might be there such as usernames and/or passwords)

**Comment by solidno8** [comment]
Tested again and still having issues, alphanumeric still works however. This is what I get when using a complex password in Plex

`Traceback (most recent call last):
  File "/usr/local/bin/trackma", line 11, in <module>
    load_entry_point('Trackma==0.7.4', 'console_scripts', 'trackma')()
  File "/usr/local/lib/python3.6/dist-packages/trackma/ui/cli.py", line 998, in main
    main_cmd.start()
  File "/usr/local/lib/python3.6/dist-packages/trackma/ui/cli.py", line 158, in start
    self.engine.start()
  File "/usr/local/lib/python3.6/dist-packages/trackma/engine.py", line 278, in start
    self.config['tracker_not_found_prompt'],
  File "/usr/local/lib/python3.6/dist-packages/trackma/tracker/plex.py", line 38, in __init__
    self.token = self._get_plex_token()
  File "/usr/local/lib/python3.6/dist-packages/trackma/tracker/plex.py", line 115, in _get_plex_token
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
`

**Comment by Hairo** [comment]
I managed to reproduce it (with a 503 error instead of 500) but it only happens when the server is not claimed and there's an username/password combo in the settings.

Is your server claimed in the player? i mean, did you login in the player?

**Comment by solidno8** [comment]
Yes, the server claimed. So "password123" works just fine whereas "?;>@%$^123" has the error above. I just tested on trackma-gtk but I believe it also happened on command line the last time I tried it.

**Comment by purposelycryptic** [comment]
Just saw this and thought I'd confirm the issue still exists: after initially setting up everything in trackma-qt (including auto-login with default AniList account) with my Plex Server account password containing symbols, it would auto-crash every time during start-up (before any action was possible) - after changing my Plex password to alphanumeric-only, and manually editing the config json accordingly, it now starts up fine.

Trackma definitely doesn't seem to like symbols in its Plex passwords, or at least certain symbols; I've had other programs work fine with most symbols, only to throw errors for others. Not sure if it helps, but the password it crashed with contained the symbols `%$*`.
