### ISSUE TITLE
Alt name trackma-curses

### ISSUE THREAD

**Issue by frstrikerman** [z411/trackma#324]
When I press 'A' to set an alternative name the app crash and I get the following logs :
`Traceback (most recent call last):
  File "/usr/bin/trackma-curses", line 11, in <module>
    load_entry_point('Trackma==0.7.4', 'console_scripts', 'trackma-curses')()
  File "/usr/lib/python3.6/site-packages/trackma/ui/curses.py", line 1123, in main
    Trackma_urwid()
  File "/usr/lib/python3.6/site-packages/trackma/ui/curses.py", line 123, in __init__
    self.mainloop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 509, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 555, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3.6/site-packages/trackma/ui/curses.py", line 270, in keystroke
    self.keymapping[input]()
  File "/usr/lib/python3.6/site-packages/trackma/ui/curses.py", line 371, in do_altname
    self.ask('[Altname] New alternative name: ', self.altname_request, self.engine.altname(showid))
NameError: name 'showid' is not defined`

**Comment by Ashymad** [comment]
This #325 PR fixes it.
