### ISSUE TITLE
Doesn't work anymore in Ubuntu 16.04

### ISSUE THREAD

**Issue by krepflap** [z411/trackma#366]
Using: trackma cli
API: Anilist
Python: Python 3.5.2

Is python 3.5 still supported ? Had to upgrade for API v2 anilist, worked fine for ages, now getting when selecting user:

```
Input account number ([r#]emember, [a]dd, [c]ancel, [d]elete, [q]uit): r1                                                                                                    
Initializing engine...                                                                                                                                                       
Engine: Trackma v0.7.6 - using account <removed>(anilist).                                                                                                                   
Engine: Reading config files...
Data: Initializing...                                                                                                                                                        
libanilist: Initializing...                                                                                                                                                  
Data: Using libanilist (anime)
libanilist: Refreshing user details...
Traceback (most recent call last):
  File ".local/bin/trackma", line 11, in <module>
    sys.exit(main())
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/ui/cli.py", line 1028, in main
    main_cmd.start()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/ui/cli.py", line 164, in start
    self.engine.start()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/engine.py", line 243, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/data.py", line 176, in start
    self.download_data()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/data.py", line 543, in download_data
    self.showlist = self.api.fetch_list()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/lib/libanilist.py", line 182, in fetch_list
    self.check_credentials()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/lib/libanilist.py", line 166, in check_credentials
    self._refresh_user_info()
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/lib/libanilist.py", line 173, in _refresh_user_info
    data = self._request(query)['data']['Viewer']
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/lib/libanilist.py", line 158, in _request
    return self._raw_request('POST', self.query_url, jsonpost=data, auth=True)
  File "/home/htpc/.local/lib/python3.5/site-packages/trackma/lib/libanilist.py", line 143, in _raw_request
    return json.load(response)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Tried deleting and adding user, removing .trackma, reinstalling with pip but doesn't make any difference. I also tried on another machine with Ubuntu 18.04 (Python 3.6.5) and that works fine.

**Comment by krepflap** [comment]
I think it has to do with some difference between Python 3.5 and Python 3.6:
https://docs.python.org/3/library/json.html#json.loads

>Changed in version 3.6: s can now be of type bytes or bytearray. The input encoding should be UTF-8, UTF-16 or UTF-32.

Error here in libanilist.py:

```
        try:
            response = self.opener.open(request, timeout = 10)
            return json.load(response)
```

Output of response.read() is in bytes.

**Comment by krepflap** [comment]
Dug at it some more. This works in 3.5 and 3.6:

```
        try:
            response = self.opener.open(request, timeout = 10)
            return json.loads(response.read().decode('utf-8'))
```

I'm not a python expert, so let me know what you think @z411

**Comment by z411** [comment]
Thank you; my bad, I thought I had applied this change. I changed it as to make it cleaner but I didn't realize it was a Python 3.6 change.
