### ISSUE TITLE
Plex - Support for Secure Connections

### ISSUE THREAD

**Issue by pascaldulieu** [z411/trackma#369]
Could support for secure connection only servers be added. Currently when a server is set to secure and the client try's to connect it dumps this into the console

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/trackma/tracker/plex.py", line 81, in observe
    self.status_log.append(self.get_plex_status())
  File "/usr/local/lib/python3.5/dist-packages/trackma/tracker/plex.py", line 44, in get_plex_status
    active = int(self._get_sessions_info("MediaContainer", "size"))
  File "/usr/local/lib/python3.5/dist-packages/trackma/tracker/plex.py", line 142, in _get_sessions_info
    info = self._get_xml_info(session_url, tag, attr)
  File "/usr/local/lib/python3.5/dist-packages/trackma/tracker/plex.py", line 130, in _get_xml_info
    uop = urllib.request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by TheVexedGerman** [comment]
@z411 This issue can probably be closed since #674 adds the option to use a secure connection with a Plex server. You will need to use a proper URL for it so the certificate matches. By default the Plex provided certificate is valid for a URL in the scheme of `[your-server-ip-address].[plex-server-id].plex.direct`. It can be found by inspecting the certificate.
