### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by matoro** [z411/trackma#372]
Getting the following error raised from the call to `sorted()` inside `_load_list()` in `ui/cli.py`:

```
Traceback (most recent call last):
  File "/usr/bin/trackma", line 11, in <module>
    load_entry_point('Trackma==0.7.4', 'console_scripts', 'trackma')()
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 1026, in main
    main_cmd.cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 727, in onecmd
    return self.execute(cmd, arg, line)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 746, in execute
    return func(args)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 282, in do_filter
    self._load_list()
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 125, in _load_list
    sortedlist = sorted(showlist, key=itemgetter(self.sort))
TypeError: '<' not supported between instances of 'int' and 'str'
```

Using python 3.7.1 .  Issue pops up on manga list, when executing `filter plantoread`.

**Comment by SynderBlack** [comment]
Cannot reproduce the error on my side. Seeing as you're on 0.7.4, the issue might have been fixed since, as we are on 0.7.6 at the moment. Please try updating.

**Comment by matoro** [comment]
@SynderBlack No luck, same on 0.7.6.  I'm sure it's one weird title in my ptr list since it has over 2k titles.  What files would you need from `~/.trackma` to be able to see it on your system?

```
-rw-r--r-- 1 matoro matoro  25K Feb  4  2018 manga.info
-rw-r--r-- 1 matoro matoro 848K Nov  6 18:07 manga.list
-rw-r--r-- 1 matoro matoro  361 Nov  6 18:07 manga.meta
-rw-r--r-- 1 matoro matoro    6 Nov  6 18:07 manga.queue
```

```
Traceback (most recent call last):
  File "/usr/bin/trackma", line 11, in <module>
    load_entry_point('Trackma==0.7.6', 'console_scripts', 'trackma')()
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 1034, in main
    main_cmd.cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 735, in onecmd
    return self.execute(cmd, arg, line)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 754, in execute
    return func(args)
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 286, in do_filter
    self._load_list()
  File "/usr/lib/python3.7/site-packages/trackma/ui/cli.py", line 129, in _load_list
    sortedlist = sorted(showlist, key=itemgetter(self.sort))
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by matoro** [comment]
@z411 This is using MAL via the fork at https://github.com/aa-zz/trackma .  Sample files are attached.
[trackma_372.zip](https://github.com/z411/trackma/files/2562217/trackma_372.zip)

**Comment by SynderBlack** [comment]
If you're using a fork, it should be the first thing you mention. Optimally you'd create the issue on that fork, since what it has implemented could be the issue.

**Comment by matoro** [comment]
Sorry, should have clarified.  Happens on latest git rev from this branch too which is where the second stack trace is from.  The fork is stuck on 0.7.4.

**Comment by Birdulon** [comment]
Three items in that `manga.list` have integers for titles. Looking at the pages on MAL, they are indeed purely numerical titles, however all titles must be stored as strings in trackma.
This is most likely a bug with the fork's makeshift website-based MAL API.

I've modified your `manga.list` to replace those titles with string representations which will probably allow viewing the list, but there's a good chance whenever the API syncs the list it will overwrite this and break it again.
[manga.list.fixed.zip](https://github.com/z411/trackma/files/2568210/manga.list.fixed.zip)

<details><summary>Click to expand detailed info</summary>

```
>>> for k in show_keys:
...   s = set([type(val[k]) for val in d.values()])
...   print(k, s)
... 
id {<class 'int'>}
title {<class 'int'>, <class 'str'>}
url {<class 'str'>}
aliases {<class 'list'>}
my_id {<class 'NoneType'>}
my_progress {<class 'int'>}
my_volumes {<class 'int'>}
my_status {<class 'int'>}
my_score {<class 'int'>}
my_start_date {<class 'NoneType'>, <class 'datetime.datetime'>}
my_finish_date {<class 'NoneType'>, <class 'datetime.datetime'>}
type {<class 'int'>}
status {<class 'int'>}
total {<class 'int'>}
total_volumes {<class 'int'>}
start_date {<class 'NoneType'>, <class 'datetime.datetime'>}
end_date {<class 'NoneType'>, <class 'datetime.datetime'>}
image {<class 'str'>}
image_thumb {<class 'str'>}
queued {<class 'bool'>}
neweps {<class 'bool'>}
my_tags {<class 'str'>}
>>> for key, value in d.items():
...   if type(value['title']) is int:
...     print(key, value)
... 
58151 {'id': 58151, 'title': 1, 'url': 'https://myanimelist.net/manga/58151/1', 'aliases': [], 'my_id': None, 'my_progress': 0, 'my_volumes': 0, 'my_status': 6, 'my_score': 0, 'my_start_date': None, 'my_finish_date': None, 'type': 0, 'status': 2, 'total': 13, 'total_volumes': 1, 'start_date': datetime.datetime(1993, 1, 8, 0, 0), 'end_date': datetime.datetime(1993, 6, 11, 0, 0), 'image': 'https://myanimelist.cdn-dena.com/images/manga/3/100697.jpg', 'image_thumb': '', 'queued': False, 'neweps': False, 'my_tags': 'Young Sunday (Weekly), 1993 Jan'}
40813 {'id': 40813, 'title': 1001, 'url': 'https://myanimelist.net/manga/40813/1001', 'aliases': [], 'my_id': None, 'my_progress': 0, 'my_volumes': 0, 'my_status': 6, 'my_score': 0, 'my_start_date': None, 'my_finish_date': None, 'type': 0, 'status': 2, 'total': 55, 'total_volumes': 10, 'start_date': datetime.datetime(2012, 6, 23, 0, 0), 'end_date': datetime.datetime(2017, 9, 23, 0, 0), 'image': 'https://myanimelist.cdn-dena.com/images/manga/3/174901.jpg', 'image_thumb': '', 'queued': False, 'neweps': False, 'my_tags': 'Asuka (Monthly), 2012 Jun'}
104039 {'id': 104039, 'title': 86, 'url': 'https://myanimelist.net/manga/104039/86', 'aliases': [], 'my_id': None, 'my_progress': 0, 'my_volumes': 0, 'my_status': 6, 'my_score': 0, 'my_start_date': None, 'my_finish_date': None, 'type': 0, 'status': 1, 'total': 0, 'total_volumes': 0, 'start_date': datetime.datetime(2017, 2, 10, 0, 0), 'end_date': None, 'image': 'https://myanimelist.cdn-dena.com/images/manga/3/194315.jpg', 'image_thumb': '', 'queued': False, 'neweps': False, 'my_tags': ''}
```

</details>

**Comment by z411** [comment]
Thank you @Birdulon ; yes, if the fork is downloading invalid titles into the cache then upstream Trackma will still give you the same error when trying to read it, which is why you get it as well. But it's the libmyanimelist of the fork that's downloading these invalid titles so I would create an issue there.

**Comment by matoro** [comment]
Thank you!  For anyone else with the same issue, this patch does the trick:  https://gist.github.com/matoro/ee947dbd97f5fa68232e2e00fc1f0c46

I appreciate you taking the time to troubleshoot even though the issue was with code that has been dropped from the repo.

**Comment by Birdulon** [comment]
It's not so much code that was dropped, the original code was for an API which no longer exists on MAL. AFAIK that fork is parsing out pages from the website to achieve similar functionality.

**Comment by z411** [comment]
Yes, MAL never got their API up and running so I decided to remove support altogether for the time being as I really don't want to deal with scraping.
