### ISSUE TITLE
App crash after adding new show

### ISSUE THREAD

**Issue by Akin2Silver** [z411/trackma#378]
Having an issue were the app crashes on launch after adding a new show to my list. 
It crashed when adding it and now crashes on open. 
Show added: Tensei Shitara Slime Datta Ken
OS: Manjaro XFCE
Built from AUR repo with `makepkg -si`
edited a few settings and added vlc to detection (sorry can't remember exactly what edits i made)
```
[ ~]$ trackma-qt
Trackma-qt v0.7.6
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
Engine: Scanning local library...
Tracker (pyinotify): Initializing...
Tracker (pyinotify): Using pyinotify.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/trackma/ui/qtui.py", line 1506, in r_engine_loaded
    self._rebuild_lists(showlist, altnames, library)
  File "/usr/lib/python3.7/site-packages/trackma/ui/qtui.py", line 681, in _rebuild_lists
    filtered_list[show['my_status']].append(show)
KeyError: 1
Aborted (core dumped)
```

Are there any other logs i can supply?
I had to manually enable the QT version for my desktop type is there an issue with compatibility? 
Sorry for noob questions, still learning about packages/desktops on Linux.

**Comment by Akin2Silver** [comment]
Also removing all files except `user.json` from `/home/lucas/.trackma/akin2silver.anilist/` and restarting the app cleared the issue and i was able to manually add the show with out any crashes.

**Comment by Akin2Silver** [comment]
still seems to be having the same issue, looks like an intermitent issue with adding new shows. 

```
[ ~]$ trackma-qt
Trackma-qt v0.7.6
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
Data: Processing queue...
libanilist: Adding item Seishun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai...
Data: Can't process Seishun Buta Yarou wa Bunny Girl-senpai no Yume wo Minai, will leave unsynced.
Engine: Scanning local library...
Tracker (pyinotify): Initializing...
Tracker (pyinotify): Using pyinotify.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/trackma/ui/qtui.py", line 1506, in r_engine_loaded
    self._rebuild_lists(showlist, altnames, library)
  File "/usr/lib/python3.7/site-packages/trackma/ui/qtui.py", line 681, in _rebuild_lists
    filtered_list[show['my_status']].append(show)
KeyError: 1
Aborted (core dumped)
```

**Comment by Akin2Silver** [comment]
Just waiting on the AUR repo to get updated and will let you know!

**Comment by FichteFoll** [comment]
`trackma-git` is always up to date. Just force a rebuild.
