### ISSUE TITLE
trackma.utils: TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by InitialFail** [z411/trackma#388]
When I launch either the Qt or GTK GUIs, I get the following stack dumps:

Qt error:

```
Traceback (most recent call last):
  File "/path/to/trackma/trackma/ui/qt/mainwindow.py", line 1308, in r_engine_loaded
    self._rebuild_view()
  File "/path/to/trackma/trackma/ui/qt/mainwindow.py", line 701, in _rebuild_view
    self.view.model().sourceModel().setShowList(showlist, altnames, library)
  File "/path/to/trackma/trackma/ui/qt/models.py", line 121, in setShowList
    self._calculate_eps(row, show)
  File "/path/to/trackma/trackma/ui/qt/models.py", line 94, in _calculate_eps
    aired_eps = utils.estimate_aired_episodes(show)
  File "/path/to/trackma/trackma/utils.py", line 198, in estimate_aired_episodes
    if eps > show['total'] and show['total'] > 0:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

GTK+3 error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/trackma/trackma/ui/gtkui.py", line 877, in task_start_engine
    self.build_all_lists()
  File "/path/to/trackma/trackma/ui/gtkui.py", line 994, in build_all_lists
    self.build_list(status)
  File "/path/to/trackma/trackma/ui/gtkui.py", line 1003, in build_list
    widget.append(show, self.engine.altname(show['id']), library.get(show['id']))
  File "/path/to/trackma/trackma/ui/gtkui.py", line 1459, in append
    aired_eps = utils.estimate_aired_episodes(show)
  File "/path/to/trackma/trackma/utils.py", line 198, in estimate_aired_episodes
    if eps > show['total'] and show['total'] > 0:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

I'm guessing it's because I have One Punch Man 2 in my Watching, which doesn't have a known total number of episodes.

I am using Anilist.

EDIT: I am using f9a48d0e6e1874f1c0401423688c545c25d97283

**Comment by z411** [comment]
Thank you. Please pull the latest commit and see if it works now.

**Comment by InitialFail** [comment]
Both Qt and GTK interfaces work now. Thanks.
