### ISSUE TITLE
KeyError: None when adding manga "flying witch" using CLI

### ISSUE THREAD

**Issue by PokeyzRule** [z411/trackma#442]
```
PokeyzRule [anilist] (manga) watching >> add "flying witch"
libanilist: Searching for flying witch...
Traceback (most recent call last):
  File "/usr/local/bin/trackma", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/trackma/ui/cli.py", line 1037, in main
    main_cmd.cmdloop()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.7/site-packages/trackma/ui/cli.py", line 758, in onecmd
    return self.execute(cmd, args, line)
  File "/usr/local/lib/python3.7/site-packages/trackma/ui/cli.py", line 775, in execute
    return func(args)
  File "/usr/local/lib/python3.7/site-packages/trackma/ui/cli.py", line 399, in do_add
    entries = self.engine.search(args[0])
  File "/usr/local/lib/python3.7/site-packages/trackma/engine.py", line 453, in search
    return self.data_handler.search(criteria, method)
  File "/usr/local/lib/python3.7/site-packages/trackma/data.py", line 215, in search
    results = self.api.search(criteria, method)
  File "/usr/local/lib/python3.7/site-packages/trackma/lib/libanilist.py", line 401, in search
    infolist.append(self._parse_info(media))
  File "/usr/local/lib/python3.7/site-packages/trackma/lib/libanilist.py", line 452, in _parse_info
    'status': self.status_translate[item['status']],
KeyError: None
```
Trackma v0.8.2

More specifically, its having trouble with the word "witch", as `add witch` produces the same crash (I was able to add it with `add flying`).

**Comment by z411** [comment]
Hi, thanks for the report. This got fixed some time ago but the update hasn't been pushed to pip yet. If you need this fixed right now you might want to try using the latest git version, otherwise I'll push the update to pip soon.

**Comment by PokeyzRule** [comment]
Thanks for the response! This bug doesn't affect me too much so I'll just wait for the update when its pushed to pip. :)

(Is this when I close the issue? New to the whole github thing 😅)
