### ISSUE TITLE
Trackma crashes

### ISSUE THREAD

**Issue by coolboymew2** [z411/trackma#443]
Here what I get when I open it:
`$ trackma-qt
Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/ui/qt/workers.py", line 184, in run
    ret = self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/ui/qt/workers.py", line 160, in _start
    self.engine.start()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/engine.py", line 238, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/data.py", line 155, in start
    self.process_queue()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/data.py", line 367, in process_queue
    self._load_cache()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/data.py", line 502, in _load_cache
    self.showlist = utils.load_data(self.cache_file)
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/utils.py", line 119, in load_data
    return pickle.load(datafile, encoding='bytes')
EOFError: Ran out of input
Aborted
`

trackma-qt gives that

trackma-gtk seems to open, but it just gets stuck at "Data: Processing queue..."

I have no idea what happened this time. Most times I find the program closed when I need it. Another time I accidentally opened an anime description by clicking a name on the qt interface (I really hate this btw, I keep accidentally opening these a doubleclick, or an option to put it to double click would be great) and immediately used my scroll wheel. Seems to be maybe an interface issue that could be causing this? I don't know

Fix:
Delete the ~/.config/trackma folder and start from scratch

Thankfully it doesn't happen all that often, but still enough that it's been the 5th time since I started using it a few months ago

Thanks!

**Comment by coolboymew2** [comment]
Well it's even worse now

While it happened I decided to update to the latest version to see if maybe that bug was fixed. Now after deleting the config folder, when I enter my credential and my anilist pin, trackma-qt suddenly closes and it gives me that:

Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/ui/qt/workers.py", line 184, in run
    ret = self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/ui/qt/workers.py", line 160, in _start
    self.engine.start()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/engine.py", line 238, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/data.py", line 143, in start
    self._load_queue()
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/data.py", line 526, in _load_queue
    self.queue = utils.load_data(self.queue_file)
  File "/usr/local/lib/python3.5/dist-packages/Trackma-0.8.2-py3.5.egg/trackma/utils.py", line 119, in load_data
    return pickle.load(datafile, encoding='bytes')
EOFError: Ran out of input
Aborted

Which seems a little bit different from last time. I'll see later if reverting to an older version permits me to continue

I wonder if it's my anilist profile that's causing this. I have a lot of entries (over 600)

**Comment by FichteFoll** [comment]
Your disk wouldn't happen to be full?

**Comment by coolboymew2** [comment]
I checked to be sure, I have a partition full but it's not where trackma is. To be sure I even deleted files there and even deleted a good chuck of unused steam games on a relevant partition is still nothing 
![Screenshot-33](https://user-images.githubusercontent.com/49840902/60305701-75b50b80-990b-11e9-9a28-d35fd22804d0.png)

Here. The stuff in media is old NTFS drive/partitions I used when I used Windows. The only part of it that's relevant to trackma is that this is where my anime are, but I don't even get to setting my anime folder, as after wiping ~/.config/trackma, the program dies immediately after entering my anilist account

Either way, it's not the first time I've had the exact same issue

------------------

Anyways, I just found out my connecting my old Kitsu account works no problem, but once I connect Anilist it dies

I tried revoking all of the tokens in my anilist account until there's nothing, then requesting a new pin and tried again, and it still doesn't work

It seems that it's my anilist account that's causing the issue

**Comment by z411** [comment]
Hi,

Where is your config directory? It seems the queue file got corrupted but if you're using the new XDG directories the file should be in `~/.local/share/trackma/<account>.anilist/<mediatype>.queue`. Try deleting it.

This happens when the file wasn't written properly/is corrupted. If you try opening it could be either empty or incomplete. Which is weird; this file gets written to every time you make a change to your list. Are you sure there isn't an issue with your filesystem/storage device?

**Comment by coolboymew2** [comment]
That worked

I deleted the whole folder ~/.local/share/trackma/, opened trackma-qt, chose my account and it worked

I suppose there's a possibility that my SSD is getting old, but I dunno, I'd probably have worse problems than that if that was truly it. Maybe something in the system interferes with trackma, but that'd be kinda weird. So far, only trackma has given me similar issues. I've had similar crashes with extremely similar error output 5-6 times so far. Although, your response seems to point to the fact that it isn't a common problem isn't it? Weird

Anyways, that worked and the program is working again. Thanks a lot!

**Comment by z411** [comment]
I **think** I've seen it happen once or twice before, but not with the frequency that you mention. It could be a bug happening in a very specific case, for example Trackma opening the file but not writing it in some specific case; I've never had it happen to me but since you might have different settings from mine, if you ever notice a pattern to it please mention it here.

**Comment by coolboymew2** [comment]
Alright, I'll be sure to report if I notice something

Once again, thanks

**Comment by coolboymew2** [comment]
Had the issue again at startup, deleted ~/.local/share/trackma/, and it worked instantly again

I wonder if trackma has issues with the OS shutting down?

Is there some sort of logs for trackma I could share? Or maybe is there a debugging function I could activate that would write logs (or more logs) to know what is happening in these instances?

Thanks

**Comment by z411** [comment]
> I wonder if trackma has issues with the OS shutting down?

Now that you mention it, that could be it. Are you shutting down your OS with Trackma open? Do you have "Send on exit" enabled? If both are positive, then that could be it; Trackma could be trying to send unsaved changes when the OS is shutting down. Then the OS might be killing Trackma while it is doing so, which would explain the corrupted queue cache. Try disabling "Send on exit"; if it doesn't happen anymore then that must be issue.

**Comment by coolboymew2** [comment]
Yup, sent on exit is enabled, I'll try deactivating it, I'll let you know if it stops happening

I've actually had some issues since switching from Linux MX XFCE it comes with to KDE. Steam, Firefox and QuiteRSS seems to block the shutdown, which then I have to close some of them, then the shutdown works after trying to shutdown again

**Comment by z411** [comment]
I see, it definitely sounds like it could be the issue. I should check to make sure that Send on Exit works only when Trackma is exited manually from the user interface; not by the OS.

**Comment by coolboymew2** [comment]
Hmm, happened again, suddenly noticed trackma was not open and it was the usual

Deleting:
~/.local/share/trackma/<account>.anilist/<mediatype>.queue

Worked

Sync is still after every change with on exit unchecked

**Comment by coolboymew2** [comment]
Trackma having some weird file recognition issue, I tried to update it since it's been a while, and it seems that trackma-qt is permanently dead now, despite deleting the .config folder and the .local/share folder

trackma-gtk works however

`Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/local/bin/trackma-qt", line 11, in <module>
    load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt')()
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/__init__.py", line 81, in main
    mainwindow = MainWindow(debug)
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 92, in __init__
    self.start(default)
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 248, in start
    self.mediatype_actiongroup = QActionGroup(self, exclusionPolicy=QActionGroup.ExclusionPolicy["Exclusive"])
AttributeError: type object 'QActionGroup' has no attribute 'ExclusionPolicy'
`

Should I open a new issue for that one since the text is slightly different than usual?

**Comment by coolboymew2** [comment]
I forgot to close it because it does not handle shut down well at all, and it crashes again

trackma-qt
Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/local/bin/trackma-qt", line 11, in <module>
    load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt')()
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/__init__.py", line 81, in main
    mainwindow = MainWindow(debug)
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 92, in __init__
    self.start(default)
  File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 248, in start
    self.mediatype_actiongroup = QActionGroup(self, exclusionPolicy=QActionGroup.ExclusionPolicy["Exclusive"])
AttributeError: type object 'QActionGroup' has no attribute 'ExclusionPolicy'

**Comment by molkoback** [comment]
Update your PyQT5

> I forgot to close it because it does not handle shut down well at all, and it crashes again
> 
> trackma-qt
> Trackma-qt v0.8.2
> Traceback (most recent call last):
> File "/usr/local/bin/trackma-qt", line 11, in
> load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt')()
> File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/**init**.py", line 81, in main
> mainwindow = MainWindow(debug)
> File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 92, in **init**
> self.start(default)
> File "/usr/local/lib/python3.7/dist-packages/Trackma-0.8.2-py3.7.egg/trackma/ui/qt/mainwindow.py", line 248, in start
> self.mediatype_actiongroup = QActionGroup(self, exclusionPolicy=QActionGroup.ExclusionPolicy["Exclusive"])
> AttributeError: type object 'QActionGroup' has no attribute 'ExclusionPolicy'

Update your PyQT5

**Comment by MyFilippo94** [comment]
I had the same issue, running through the code I determined the file user.anilist/anime.list was the culprit, and indeed it was 0 bytes large. Deleting it solved the problem.

The trigger in my case was faulty internet connection. I'm running in a virtual machine, and sharing the adapter through a bridge. The adapter is not the most bright bulb on my computer, and sometimes needs a reboot to get it to work again.

Trackma tried to update the list, but failed. I noticed there was no connection, so I closed everything, shut down the VM, and rebooted the host. When back in my VM I got this error:
`Trackma v0.8.4  Copyright (C) 2012-2020  z411
This program comes with ABSOLUTELY NO WARRANTY; for details type `about'
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing engine...
Engine: Trackma v0.8.4 - using account [username](anilist).
Engine: Reading config files...
Data: Initializing...
libanilist: Initializing...
Data: Using libanilist (anime)
Data: Processing queue...
Traceback (most recent call last):
  File "/usr/bin/trackma", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.4', 'console_scripts', 'trackma')())
  File "/usr/lib/python3.9/site-packages/trackma/ui/cli.py", line 1069, in main
    main_cmd.start()
  File "/usr/lib/python3.9/site-packages/trackma/ui/cli.py", line 180, in start
    self.engine.start()
  File "/usr/lib/python3.9/site-packages/trackma/engine.py", line 248, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib/python3.9/site-packages/trackma/data.py", line 158, in start
    self.process_queue()
  File "/usr/lib/python3.9/site-packages/trackma/data.py", line 371, in process_queue
    self._load_cache()
  File "/usr/lib/python3.9/site-packages/trackma/data.py", line 510, in _load_cache
    self.showlist = utils.load_data(self.cache_file)
  File "/usr/lib/python3.9/site-packages/trackma/utils.py", line 142, in load_data
    return pickle.load(datafile, encoding='bytes')
EOFError: Ran out of input
`
I did reach for utils.py and put a print(filename) command in the load_data function before it did its thing. The last opened file was indeed anime.list, so I discovered the source of the issue, and managed to get it working again.

**Comment by FichteFoll** [comment]
That's really useful. There should probably be an exception handler for corrupted config/cache files that just deletes them if they are faulty and cannot be read.

**Comment by coolboymew2** [comment]
Oddly enough, I've stopped having the problems in the last few releases of Trackma so far
