### ISSUE TITLE
Anilist not downloading

### ISSUE THREAD

**Issue by FACorreiaa** [z411/trackma#483]
Engine: Reading config files...
Data: Initializing...
libanilist: Initializing...
Data: Using libanilist (anime)
libanilist: Downloading list...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fernando/.local/lib/python3.6/site-packages/trackma/ui/gtk/mainview.py", line 138, in _engine_start_task
    self._engine.start()
  File "/home/fernando/.local/lib/python3.6/site-packages/trackma/engine.py", line 238, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/home/fernando/.local/lib/python3.6/site-packages/trackma/data.py", line 175, in start
    self.download_data()
  File "/home/fernando/.local/lib/python3.6/site-packages/trackma/data.py", line 543, in download_data
    self.showlist = self.api.fetch_list()
  File "/home/fernando/.local/lib/python3.6/site-packages/trackma/lib/libanilist.py", line 291, in fetch_list
    'type': self.type_translate[media['format']],
KeyError: None

Any help on why ? Im on Linux

**Comment by ahmubashshir** [comment]
Maybe it's for unsupported mediatype. Can you try my fork #480 or #481 ?

**Comment by alltimemarr** [comment]
Hello! New user here.

I have the same issue;

`  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/trackma/ui/gtk/window.py", line 269, in _synchronization_task
    self._engine.list_download()
  File "/usr/local/lib/python3.8/site-packages/trackma/engine.py", line 935, in list_download
    self.data_handler.download_data()
  File "/usr/local/lib/python3.8/site-packages/trackma/data.py", line 543, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/local/lib/python3.8/site-packages/trackma/lib/libanilist.py", line 292, in fetch_list
    'status': self.status_translate[media['status']],
KeyError: None`

My mangalist does get pulled/downloaded correctly.

Also, with MAL api being back up, will we be able to download our list/update to MAL again too?

**Comment by z411** [comment]
Sorry I just got time to look into this. Can you check if https://github.com/z411/trackma/commit/cd3a3c005a6073d3b53c001be1308fc111592292 fixed your issue?

**Comment by z411** [comment]
Closing for lack of feedback; should be fixed.
