### ISSUE TITLE
trackma crashes after playing video file

### ISSUE THREAD

**Issue by afromanDAN** [z411/trackma#489]
Hello, I'm getting this python error. I reinstalled to no avail. I am using arch linux and KDE.

`Engine: Getting Toaru Majutsu no Index II 15 from library...
Engine: Found. Starting player...
Tracker (pyinotify): Will update Toaru Majutsu no Index II 15
Tracker (pyinotify): Not playing the next episode of Toaru Majutsu no Index II. Ignoring.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Trackma-0.8.2-py3.8.egg/trackma/ui/qt/mainwindow.py", line 1306, in ws_tracker_state
    self._update_tracker_info(status)
  File "/usr/lib/python3.8/site-packages/Trackma-0.8.2-py3.8.egg/trackma/ui/qt/mainwindow.py", line 607, in _update_tracker_info
    (m, s) = divmod(timer, 60)
TypeError: unsupported operand type(s) for divmod(): 'NoneType' and 'int'
Aborted (core dumped)`

**Comment by afromanDAN** [comment]
Some how got fixed on a newer git build.
