### ISSUE TITLE
trackma-qt crashes upon start

### ISSUE THREAD

**Issue by NovaMoon** [z411/trackma#506]
new install on arch from the AUR. also crashes by installing through pip or source code

`Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/bin/trackma-qt", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt')())
  File "/home/nova/.local/lib/python3.8/site-packages/trackma/ui/qt/__init__.py", line 79, in main
    mainwindow = MainWindow(debug)
  File "/home/nova/.local/lib/python3.8/site-packages/trackma/ui/qt/mainwindow.py", line 91, in __init__
    self.start(default)
  File "/home/nova/.local/lib/python3.8/site-packages/trackma/ui/qt/mainwindow.py", line 247, in start
    self.mediatype_actiongroup = QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument`

**Comment by molkoback** [comment]
That was already fixed in https://github.com/z411/trackma/commit/54b7e1af334519c06387224a4ec2a2509633d91a
Delete everything trackma and pyqt5 related from /home/nova/.local/lib/python3.8/site-packages and try again
