### ISSUE TITLE
Adding pypresence to a hook crashes UI frontends

### ISSUE THREAD

**Issue by slapelachie** [z411/trackma#522]
In reference to https://github.com/z411/trackma/pull/519#issuecomment-725903189, importing and using the pypresence library to a hook crashes the frontend. Doing a bit of researching online it seems it may be because the ui-frontends are not multi-threaded (found [here](https://www.tutorialfor.com/questions-296414.htm)). The following is the error outputed.
```
/home/username/.local/lib/python3.8/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/trackma/ui/gtk/mainview.py", line 154, in _engine_start_task
    self._engine.start()
  File "/home/username/.local/lib/python3.8/site-packages/trackma/engine.py", line 304, in start
    module = loader.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/username/.config/trackma/hooks/discord.py", line 12, in <module>
    RPC = Presence(client_id)
  File "/home/username/.local/lib/python3.8/site-packages/pypresence/presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 37, in __init__
    self.update_event_loop(self.get_event_loop())
  File "/home/username/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 73, in get_event_loop
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

**Comment by z411** [comment]
I think it's the other way around. Both Qt and GTK interfaces are multithreaded (worker thread and new-thread-per-task, respectively), while the CLI and curses interfaces are not. So it seems that pypresence doesn't like to be started from inside a thread.

One fix would be to switch to the multiprocessing module to have Trackma's engine in a separate subprocess rather than a thread; that way pypresence should work. The Qt interface already uses a single worker thread for the engine so moving that to a subprocess should be trivial. The GTK interface should need more work though, but it should be done as a single worker thread/subprocess for the engine is a better solution in my eyes.

Lastly, I always wanted to switch Trackma into a server-client architecture and as a side effect it would make this a non-issue, but that's a longer term goal.

I'll look into it.

**Comment by ahmubashshir** [comment]
`pypresense` crashed cause it couldn't get a asyncio event loop...

```python 3
from asyncio import (
    new_event_loop as new_loop,
    set_event_loop as set_loop )

set_loop(new_loop())
```

**Comment by slapelachie** [comment]
This does fix the problem and hook gets successfully imported with this. Thanks.

**Comment by z411** [comment]
I indeed saw that workaround but iirc asyncio explicitly doesn't start a loop if it's not running from the main thread, since subprocess signals don't work on Linux in secondary threads. That said if this module works with this then we should consider this fixed.
