### ISSUE TITLE
Error when searching for Nichijou on MAL

### ISSUE THREAD

**Issue by Skaytacium** [z411/trackma#532]
When searching for "Nichijou" or "nichijou" or "nichi" it raises a KeyError: 'unknown'

` [mal] (anime) watching >> add Nichijou
libmal: Searching for Nichijou...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\trackma-script.py", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.4', 'console_scripts', 'trackma')())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\ui\cli.py", line 1079, in main
    main_cmd.cmdloop()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\ui\cli.py", line 780, in onecmd
    return self.execute(cmd, args, line)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\ui\cli.py", line 797, in execute
    return func(args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\ui\cli.py", line 409, in do_add
    entries = self.engine.search(args[0])
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\engine.py", line 482, in search
    return self.data_handler.search(criteria, method)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\data.py", line 219, in search
    results = self.api.search(criteria, method)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\lib\libmal.py", line 318, in search
    results.append(self._parse_info(item['node']))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trackma-0.8.4-py3.9.egg\trackma\lib\libmal.py", line 365, in _parse_info
    'type': self.type_translate[item['media_type']],
KeyError: 'unknown'`

Version: straight from GitHub. Ran setup.py with python 3.9 and install.
OS: Windows 10 20H2
Other: Using windows terminal and a modified PS, but has the same result when using engine.search()

Other things I tried: using python 3.8.6

Any help would be greatly appreciated.

**Comment by Skaytacium** [comment]
Also, when it doesn't have any results (the search function), it returns this and terminates instead of an error/event.

`Traceback (most recent call last):
  File "C:\Python38\Scripts\trackma-script.py", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.4', 'console_scripts', 'trackma')())
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\ui\cli.py", line 1079, in main
    main_cmd.cmdloop()
  File "C:\Python38\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\ui\cli.py", line 780, in onecmd
    return self.execute(cmd, args, line)
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\ui\cli.py", line 797, in execute
    return func(args)
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\ui\cli.py", line 409, in do_add
    entries = self.engine.search(args[0])
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\engine.py", line 482, in search
    return self.data_handler.search(criteria, method)
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\data.py", line 219, in search
    results = self.api.search(criteria, method)
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\lib\libmal.py", line 318, in search
    results.append(self._parse_info(item['node']))
  File "C:\Python38\lib\site-packages\trackma-0.8.4-py3.8.egg\trackma\lib\libmal.py", line 368, in _parse_info
    'image': item['main_picture']['large'],
KeyError: 'main_picture'`

OS Info and others are the same as above

**Comment by mobrine1** [comment]
I think I can add a contribution if we knew how we exactly want to fix this issue.
The problem is when you add a tittle, what's happening in the background is that it searches for a the query you specified.
There are two ways to handle this:
- Either to print all results and ask you to choose a specific one
- Take your query and match it literally with titles found (You can add wrong title to your list, if you used half word)

**Comment by z411** [comment]
Fixed by #545

**Comment by Skaytacium** [comment]
Great!
