### ISSUE TITLE
Cannot open trackma-qt on KDE

### ISSUE THREAD

**Issue by Archerious** [z411/trackma#556]
```
kazuma@pop-os:~$ trackma-qt
Traceback (most recent call last):
  File "/home/kazuma/.local/lib/python3.8/site-packages/trackma/ui/qt/workers.py", line 25, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kazuma/.local/bin/trackma-qt", line 5, in <module>
    from trackma.ui.qt import main
  File "/home/kazuma/.local/lib/python3.8/site-packages/trackma/ui/qt/__init__.py", line 18, in <module>
    from trackma.ui.qt.mainwindow import MainWindow
  File "/home/kazuma/.local/lib/python3.8/site-packages/trackma/ui/qt/mainwindow.py", line 21, in <module>
    from trackma.ui.qt.workers import EngineWorker, ImageWorker
  File "/home/kazuma/.local/lib/python3.8/site-packages/trackma/ui/qt/workers.py", line 27, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
kazuma@pop-os:~$ pip3 install Trackma
Requirement already satisfied: Trackma in ./.local/lib/python3.8/site-packages (0.8.4)
kazuma@pop-os:~$ 
```

**Comment by Archerious** [comment]
Fixed with `pip3 install image`.

**Comment by ahmubashshir** [comment]
Just install python-pillow or python3-pillow depending on your distro
