### ISSUE TITLE
Trackma-GTK Broken

### ISSUE THREAD

**Issue by Archerious** [z411/trackma#559]
```
#trackma-gtk
/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Traceback (most recent call last):
  File "/home/kazuma/.local/bin/trackma-gtk", line 5, in <module>
    from trackma.ui.gtk.main import main
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/main.py", line 19, in <module>
    from trackma.ui.gtk.application import TrackmaApplication
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/application.py", line 18, in <module>
    from trackma.ui.gtk.window import TrackmaWindow
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/window.py", line 25, in <module>
    from trackma.ui.gtk.accountswindow import AccountsWindow
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/accountswindow.py", line 34, in <module>
    class AccountsWindow(Gtk.Dialog):
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__
    _register_template(cls, template_bytes)
  File "/home/kazuma/.local/lib/python3.9/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template
    cls.set_connect_func(_connect_func, cls)
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func'
```

Latest trackma from pip installed at the moment. Arch linux is my distro.

**Comment by ahmubashshir** [comment]
Install aur/trackma-git... or install from git.

**Comment by Archerious** [comment]
That resolved it, thank you :).
