### ISSUE TITLE
Error download list

### ISSUE THREAD

**Issue by clebermatheus** [z411/trackma#561]
Version: v0.8.4
Python: 3.9
Traker: MyAnimeList (anime)
OS: Arch Linux

```
Trackma v0.8.4  Copyright (C) 2012-2020  z411
This program comes with ABSOLUTELY NO WARRANTY; for details type `about'
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing engine...
Engine: Trackma v0.8.4 - using account clebermatheus(mal).
Engine: Reading config files...
Data: Initializing...
libmal: Initializing...
Data: Using libmal (anime)
libmal: Downloading list (page 1)...
Traceback (most recent call last):
  File "/usr/bin/trackma", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.4', 'console_scripts', 'trackma')())
  File "/usr/lib/python3.9/site-packages/trackma/ui/cli.py", line 1069, in main
    main_cmd.start()
  File "/usr/lib/python3.9/site-packages/trackma/ui/cli.py", line 180, in start
    self.engine.start()
  File "/usr/lib/python3.9/site-packages/trackma/engine.py", line 248, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib/python3.9/site-packages/trackma/data.py", line 179, in start
    self.download_data()
  File "/usr/lib/python3.9/site-packages/trackma/data.py", line 552, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python3.9/site-packages/trackma/lib/libmal.py", line 266, in fetch_list
    'image': item['node']['main_picture']['large'],
KeyError: 'main_picture'
```

**Comment by DavidBonelo** [comment]
Same issue in Fedora 34
I installed from source, but it was working before 🤔
Python 3.9.6
MAL(Anime)
CLI, GTK, qt

```
yeru@fedora ~ [1]> trackma -d
Trackma v0.8.4  Copyright (C) 2012-2020  z411
This program comes with ABSOLUTELY NO WARRANTY; for details type `about'
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing engine...
Engine: Trackma v0.8.4 - using account yeruk(mal).
Engine: Reading config files...
Data: Initializing...
[D] Data: Reading userconfig...
libmal: Initializing...
Data: Using libmal (anime)
[D] Data: Locking database...
[D] Data: Reading metadata...
[D] Data: Reading queue...
[D] Data: Reading info DB...
[D] Data: No items in queue.
[D] Data: No items in queue.
libmal: Downloading list (page 1)...
[D] libmal: GET URL: https://api.myanimelist.net/v2/users/@me/animelist?fields=id%2Calternative_titles%2Ctitle%2Cmain_picture%2Cnum_episodes%2Cstatus%2Clist_status%7Bnum_episodes_watched%2Cscore%2Cstatus%2Cstart_date%2Cfinish_date%7D&limit=1000
Traceback (most recent call last):
  File "/usr/local/bin/trackma", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.4', 'console_scripts', 'trackma')())
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/ui/cli.py", line 1069, in main
    main_cmd.start()
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/ui/cli.py", line 180, in start
    self.engine.start()
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/engine.py", line 249, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/data.py", line 169, in start
    self.download_data()
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/data.py", line 552, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/local/lib/python3.9/site-packages/Trackma-0.8.4-py3.9.egg/trackma/lib/libmal.py", line 266, in fetch_list
    'image': item['node']['main_picture']['large'],
KeyError: 'main_picture'
yeru@fedora ~ [1]> 

```

**Comment by TheTabbingman** [comment]
I was having this issue on windows and resolved it by removing this from my list
https://myanimelist.net/anime/49733/Yuukoku_no_Moriarty_OVA
