### ISSUE TITLE
Trackma GTK does not load properly under GTK 4.0

### ISSUE THREAD

**Issue by Parent5446** [z411/trackma#562]
When `trackma-gtk` loads, it doesn't specify a specific GTK version to load from `gi.repository`, so it always loads the latest version. And the app is currently broken under GTK 4.0.

Running the app on Fedora 34 (which has now upgraded to GNOME 40 and GTK 4.0), gives the following stack trace:

```
/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Traceback (most recent call last):
  File "/home/parent5446/.local/bin/trackma-gtk", line 5, in <module>
    from trackma.ui.gtk.main import main
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/main.py", line 19, in <module>
    from trackma.ui.gtk.application import TrackmaApplication
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/application.py", line 18, in <module>
    from trackma.ui.gtk.window import TrackmaWindow
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/window.py", line 25, in <module>
    from trackma.ui.gtk.accountswindow import AccountsWindow
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/accountswindow.py", line 34, in <module>
    class AccountsWindow(Gtk.Dialog):
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__
    _register_template(cls, template_bytes)
  File "/home/parent5446/.local/lib/python3.9/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template
    cls.set_connect_func(_connect_func, cls)
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func'
```

**Comment by Parent5446** [comment]
Ah woops looks like this was fixed indirectly by #538 by cf2cbd5 but hasn't made it into a release yet. I'll just wait for the next release.
