### ISSUE TITLE
[Kitsu] libkitsu.py is missing the type_translate dict

### ISSUE THREAD

**Issue by bubi-soft** [z411/trackma#604]
hello
i tried to use Trakma GTK with kitsu account under Manjaro XFCE 21.2.4
Got the following error in CLI while the interface is stuck at getting page 1
```
$ trackma-gtk
Trackma GTK v0.8.4
Engine: Trackma v0.8.4 - using account (kitsu).
Engine: Reading config files...
Data: Initializing...
libkitsu: Initializing...
Data: Using libkitsu (anime)
libkitsu: Downloading list...
libkitsu: Getting page 1...
Exception in thread Thread-1 (_engine_start_task):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/mainview.py", line 160, in _engine_start_task
    self._engine.start()
  File "/usr/lib/python3.10/site-packages/trackma/engine.py", line 249, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib/python3.10/site-packages/trackma/data.py", line 179, in start
    self.download_data()
  File "/usr/lib/python3.10/site-packages/trackma/data.py", line 552, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib/python3.10/site-packages/trackma/lib/libkitsu.py", line 355, in fetch_list
    info = self._parse_info(media)
  File "/usr/lib/python3.10/site-packages/trackma/lib/libkitsu.py", line 559, in _parse_info
    'type':        self.type_translate.get(attr['subtype'], utils.TYPE_UNKNOWN),
AttributeError: 'libkitsu' object has no attribute 'type_translate'. Did you mean: 'status_translate'?
```

After a little bit of searching around the code base it looks like ```type_translate``` dict is missing.
As a workaround I copied the dict from the libmal.py and updated the `utils.TYPE_UNKNOWN -> utils.Type.UNKNOWN`  and `utils.STATUS_UNKNOWN -> utils.Status.UNKNOWN`.
And now it seems to work.
```
$ trackma-gtk
Trackma GTK v0.8.4
Engine: Trackma v0.8.4 - using account (kitsu).
Engine: Reading config files...
Data: Initializing...
libkitsu: Initializing...
Data: Using libkitsu (anime)
libkitsu: Downloading list...
libkitsu: Getting page 1...
libkitsu: Getting page 2...
libkitsu: Getting page 3...
Engine: Parsing redirection file...
Engine: Scanning local library...
Tracker (pyinotify): Initializing...
Tracker (pyinotify): Using pyinotify.
Ready.
```

**Comment by FichteFoll** [comment]
I think the enum PR that was merged was a bit unfinished. I haven't had the time to go over that yet and compare it with my proposed changes, but I intend to do that hopefully sooner rather than later. For the record, I'm referring to #491 and #527.

**Comment by z411** [comment]
Fixed. If the problem persists feel free to reopen.
