### ISSUE TITLE
Getting OSError: [WinError 193] whenever I try to play anything

### ISSUE THREAD

**Issue by cuanim** [z411/trackma#605]
`OSError: [WinError 193] %1 is not a valid Win32 application`  to be exact

I am on the git version but got the same error on pypi version too.

Config file: 
```json
{
    "auto_date_change": true,
    "auto_status_change": true,
    "auto_status_change_if_scored": true,
    "autoretrieve": "days",
    "autoretrieve_days": 3,
    "autosend": "minutes",
    "autosend_at_exit": true,
    "autosend_minutes": 60,
    "autosend_size": 5,
    "debug_disable_lock": true,
    "jellyfin_api_key": "",
    "jellyfin_apikey": "",
    "jellyfin_host": "localhost",
    "jellyfin_port": "8096",
    "jellyfin_user": "",
    "kodi_host": "localhost",
    "kodi_obey_update_wait_s": false,
    "kodi_passwd": "",
    "kodi_port": "8080",
    "kodi_user": "",
    "library_autoscan": true,
    "library_full_path": true,
    "player": "",
    "plex_host": "localhost",
    "plex_obey_update_wait_s": false,
    "plex_passwd": "",
    "plex_port": "32400",
    "plex_user": "",
    "plex_uuid": "aec316e1-9ba1-11ec-a3ca-84c5a60bbbf7",
    "redirections_time": 1,
    "redirections_url": "https://raw.githubusercontent.com/erengy/anime-relations/master/anime-relations.txt",
    "scan_whole_list": false,
    "searchdir": [
        "E:/z. Misc/anime"
    ],
    "tracker_enabled": true,
    "tracker_ignore_not_next": true,
    "tracker_interval": 10,
    "tracker_not_found_prompt": false,
    "tracker_process": "mplayer|mplayer2|mpv",
    "tracker_type": "win32",
    "tracker_update_close": false,
    "tracker_update_prompt": false,
    "tracker_update_wait_s": 120,
    "use_hooks": true
}
```
and here's the command line output if it helps
```
E:\z. Misc\anime>trackma -d -a 1
Trackma v0.8.4  Copyright (C) 2012-2020  z411
This program comes with ABSOLUTELY NO WARRANTY; for details type `about'
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Initializing engine...
Engine: Trackma v0.8.4 - using account cuanim(anilist).
Engine: Reading config files...
Data: Initializing...
[D] Data: Reading userconfig...
libanilist: Initializing...
Data: Using libanilist (anime)
[D] Data: Locking database...
[D] Data: Reading metadata...
libanilist: Downloading list...
[D] Data: Saving userconfig...
[D] Data: Saving cache...
[D] Data: Saving metadata...
Engine: Parsing redirection file...
Engine: Scanning local library...
[D] Engine: Scanning for Watching
[D] Engine: Scanning for Rewatching
[D] Engine: Scanning for Paused
[D] Engine: Scanning for Plan to Watch
[D] Engine: Directory: E:/z. Misc/anime
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 01 [BD 1080p AAC] [6EE06D1F].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 02 [BD 1080p AAC] [7E119FF0].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 03 [BD 1080p AAC] [6767AB1F].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 04 [BD 1080p AAC] [6C6891E3].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 05 [BD 1080p AAC] [FC5D8073].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 06 [BD 1080p AAC] [3AAA5196].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 07 [BD 1080p AAC] [4DDBAA16].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 08 [BD 1080p AAC] [17D889D0].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 09 [BD 1080p AAC] [7A5ADBD3].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 10 [BD 1080p AAC] [99FD556C].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 11 [BD 1080p AAC] [089C3B5C].mkv
[D] Engine: File in cache: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 12 [BD 1080p AAC] [BD72906C].mkv
[D] Engine: Time: 0.004000425338745117
[D] Engine: Initializing tracker...
Tracker (win32): Initializing...
[D] Tracker (win32): Enabling tracker...
Tracker (win32): Using Win32.

Ready. Type 'help' for a list of commands.
Press tab for autocompletion and up/down for command history.
Available statuses: watching, completed, rewatching, paused, dropped, plantowatch

cuanim [anilist] (anime) watching >> ls
| Index  Title                                           Progress  Score  |
|   1    Girls' Weekend Class...........................   2 / 12    0    |
|   2    How Clumsy you are, Miss Ueno..................   2 / 12    0    |
|   3    Hugtto! Precure................................   3 / 49    0    |
|   4    Lupin the 3rd Part IV..........................   9 / 24    0    |
|   5    Revolutionary Girl Utena [Shoujo Kakumei Utena]   9 / 39    0    |
|   6    The Legend of Luoxiaohei.......................  18 / 28    0    |
|   7    Tree in the Sun................................   5 / 25    0    |
7 results

cuanim [anilist] (anime) watching >> rescan
Engine: Scanning local library (overriding cache)...
[D] Engine: Scanning for Watching
[D] Engine: Scanning for Rewatching
[D] Engine: Scanning for Paused
[D] Engine: Scanning for Plan to Watch
[D] Engine: Directory: E:/z. Misc/anime
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 01 [BD 1080p AAC] [6EE06D1F].mkv
[D] Engine: Redirected to: Girls' Weekend Class 1
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 02 [BD 1080p AAC] [7E119FF0].mkv
[D] Engine: Redirected to: Girls' Weekend Class 2
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 03 [BD 1080p AAC] [6767AB1F].mkv
[D] Engine: Redirected to: Girls' Weekend Class 3
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 04 [BD 1080p AAC] [6C6891E3].mkv
[D] Engine: Redirected to: Girls' Weekend Class 4
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 05 [BD 1080p AAC] [FC5D8073].mkv
[D] Engine: Redirected to: Girls' Weekend Class 5
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 06 [BD 1080p AAC] [3AAA5196].mkv
[D] Engine: Redirected to: Girls' Weekend Class 6
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 07 [BD 1080p AAC] [4DDBAA16].mkv
[D] Engine: Redirected to: Girls' Weekend Class 7
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 08 [BD 1080p AAC] [17D889D0].mkv
[D] Engine: Redirected to: Girls' Weekend Class 8
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 09 [BD 1080p AAC] [7A5ADBD3].mkv
[D] Engine: Redirected to: Girls' Weekend Class 9
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 10 [BD 1080p AAC] [99FD556C].mkv
[D] Engine: Redirected to: Girls' Weekend Class 10
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 11 [BD 1080p AAC] [089C3B5C].mkv
[D] Engine: Redirected to: Girls' Weekend Class 11
[D] Engine: Adding to library: E:/z. Misc/anime\Shoujo Shuumatsu Jugyou\[Asenshi] Shoujo Shuumatsu Jugyou - 12 [BD 1080p AAC] [BD72906C].mkv
[D] Engine: Redirected to: Girls' Weekend Class 12
[D] Engine: Time: 0.7063920497894287
cuanim [anilist] (anime) watching >> play "Girls' Weekend Class"
Engine: Getting Girls' Weekend Class 3 from library...
Engine: Found. Starting player...
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\Scripts\trackma.exe\__main__.py", line 7, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\trackma\ui\cli.py", line 1079, in main
    main_cmd.cmdloop()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\trackma\ui\cli.py", line 780, in onecmd
    return self.execute(cmd, args, line)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\trackma\ui\cli.py", line 797, in execute
    return func(args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\trackma\ui\cli.py", line 525, in do_play
    utils.spawn_process(args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\trackma\utils.py", line 452, in spawn_process
    subprocess.Popen(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by FichteFoll** [comment]
I think you have to configure the path to the player in the `"player"` setting.

**Comment by cuanim** [comment]
🤦‍♂️ yeah that fixed it, my bad. Thanks
