### ISSUE TITLE
help

### ISSUE THREAD

**Issue by autoteelar** [z411/trackma#645]
i set it to remember tabs location, then i pressed manga and it crashed (shikimori)

and now it crashes every time

**Comment by autoteelar** [comment]
using qt

**Comment by autoteelar** [comment]
gtk crashed and still crashes before this even happened with 
$ trackma-gtk
/usr/lib/python3.10/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Traceback (most recent call last):
  File "/bin/trackma-gtk", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.3', 'gui_scripts', 'trackma-gtk')())
  File "/bin/trackma-gtk", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/main.py", line 19, in <module>
    from trackma.ui.gtk.application import TrackmaApplication
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/application.py", line 18, in <module>
    from trackma.ui.gtk.window import TrackmaWindow
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/window.py", line 25, in <module>
    from trackma.ui.gtk.accountswindow import AccountsWindow
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/accountswindow.py", line 34, in <module>
    class AccountsWindow(Gtk.Dialog):
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__
    _register_template(cls, template_bytes)
  File "/usr/lib/python3.10/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template
    cls.set_connect_func(_connect_func, cls)
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func'

**Comment by FichteFoll** [comment]
Try the latest version 0.8.5 first.

**Comment by autoteelar** [comment]
ok thanks, my package manager has 0.8.4 right now
