### ISSUE TITLE
Can't do setup install on my manjaro

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#675]
```
$ git pull
Already up to date.
```
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
```
$ sudo python setup.py install
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "trackma/setup.py", line 20, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
packaging.version.InvalidVersion: Invalid version: '.9' (package: amt)
```

**Comment by FichteFoll** [comment]
First, I don't recommend installing Python packages manually with `sudo` because that will install files on your system that your package manager won't know about. Instead, omit the `sudo` to make a user installation.

Second, please try again with the updated instructions after #653 has been merged.

**Comment by v-fox** [comment]
> First, I don't recommend installing Python packages manually with `sudo` because that will install files on your system that your package manager won't know about. Instead, omit the `sudo` to make a user installation.
> 
> Second, please try again with the updated instructions after #653 has been merged.
> 
> Third, you'd generally be more interested in installing trackma using your system's package manager and the [`trackma` AUR package](https://aur.archlinux.org/packages/trackma).

System package manager that installs packages built with `python setup.py install` which relies on setup.py which was nonchalantly nuked in https://github.com/z411/trackma/commit/084e3511673dfa9673fa6cf85c58ee8b3ef637ec
How are we supposed to package it in distros now?

**Comment by FichteFoll** [comment]
See https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517) for the relevant instructions for Arch packaging (and [here for the code of `trackma-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=trackma-git)).

**Comment by v-fox** [comment]
> See https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517) for the relevant instructions for Arch packaging (and [the code of the `trackma-git` package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=trackma-git)).
> 
> Edit: see also the [PyPA packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

I'm using [openSUSE on Open Build Service](https://github.com/openSUSE/python-rpm-macros). It has `%pyproject_wheel` & `%pyproject_install` macros to supposedly replace `%python_build` & `%python_install` BUT have not seen a single official or unofficial package use it. When trying out it tried to make builds for absent versions of python without automatically pulling the dependencies and there is not obvious example to make a proper spec-file. But openSUSE manuals are traditionally written in weird impenetrable style that loses the point and may be factually wrong even when not obsolete.
`python-poetry-core` seems to be a hard dependency for such build and it's not in any of official repos which means it has to be packaged too and for all distro-supported versions of python. And who knows what absent dependencies it may have.

I doubt that distros would change entire way of handling python packages for an app that is barely maintained or absent from official repos altogether. Personally, for my package I just put back the removed file and left it as is.

**Comment by FichteFoll** [comment]
Using `setup.py` to install packages has been deprecated a while ago and PEP-517 is the way forward. This is nothing that is specific for trackma, it's a general movement in the Python world and `setup.py` is not coming back, if you ask me.

I find it concerning that OpenSUSE wouldn't have any packaging guidelines or a single package using this new build format. Unfortunately, my experience with OpenSUSE is exactly zero, so I can't provide any help with it.

**Comment by txtsd** [comment]
> System package manager that installs packages built with `python setup.py install` which relies on setup.py which was nonchalantly nuked in [084e351](https://github.com/z411/trackma/commit/084e3511673dfa9673fa6cf85c58ee8b3ef637ec) How are we supposed to package it in distros now?

That was me bringing the package up to Python standards. I'm sorry it's causing problems with packaging on OpenSUSE, but distros ought to move forward when standards are set.

Instead of substituting the removed `setup.py` back in, why not `pip install --user poetry` in the build process, and then use `poetry` to build normally?

**Comment by txtsd** [comment]
> What average users definitively should not be doing is crapping their /home directory with 3rd-party managers and unnecessary copies of dependencies. This is MacOS & Windows habit stemming from dll-hell and lack of proper system management.
> 
> However, just for the heck of it, I tried out to make a working package in new style. It was a complete shit-show but in the end it worked. I present you with [this ugly monstrosity](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/trackma) which is bloated and overly complex in comparison to [the original](https://build.opensuse.org/package/view_file/home:X0F:branches:multimedia/trackma/trackma.spec?expand=1&rev=d631ea99a2b017523f1ac3c8428858d6):
> trackma.spec

Are you even happy with openSUSE? This seems like a lot of work to get one thing building and working correctly. I've looked into OBS in the past to automate Prism Launcher builds across distros and maintained versions of distros, but the syntax and the macros really put me off.
