### ISSUE TITLE
trackma-gtk doesn't load

### ISSUE THREAD

**Issue by trespordez** [z411/trackma#695]
Installed using pip; When i run `trackma-gtk` on terminal, this happens:
```
Trackma GTK v0.8.5                                                                                                                                   

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.345: Theme parsing error: gtk.css:6                                                                     187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.345: Theme parsing error: gtk.css:6                                                                     191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.345: Theme parsing error: gtk.css:6                                                                     191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.345: Theme parsing error: gtk.css:6                                                                     195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.345: Theme parsing error: gtk.css:6                                                                     205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                         

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                         

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.346: Theme parsing error: gtk.css:6                                                                     224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                         

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                         

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.347: Theme parsing error: gtk.css:6                                                                     244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.                                                                          

(trackma-gtk:5776): Gtk-WARNING **: 22:17:59.348: Theme parsing error: gtk.css:6                                                                     244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Traceback (most recent call last):                                                                                                                   
  File "/home/leandson/.local/lib/python3.8/site-packages/trackma/ui/gtk/applica                                                                     tion.py", line 53, in do_activate                                                                                                                    
    self.create_window()                                                                                                                             
  File "/home/leandson/.local/lib/python3.8/site-packages/trackma/ui/gtk/applica                                                                     tion.py", line 92, in create_window                                                                                                                  
    self.window = TrackmaWindow(self, self.debug)                                                                                                    
  File "/home/leandson/.local/lib/python3.8/site-packages/trackma/ui/gtk/window.                                                                     py", line 48, in __init__                                                                                                                            
    self.init_template()                                                                                                                             
TypeError: <lambda>() missing 1 required positional argument: 's'
```

SO: Bodhi Linux 6.0 (based on Ubuntu 20.04)
Installed trough `pip`,  All dependencies installed

**Comment by FichteFoll** [comment]
That's a very weird traceback. First of all, the log seem to be cut off on the right side. Second of all, there is no lumbda at the indicated position.

And finally, I cannot reproduce this on Arch Linux and current `master`.

Please provide a full debug log (launch `trackma-gtk -d 2>&1 | tee trackma.log`).
