### ISSUE TITLE
Poster image doesn't load -- module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by uzuto** [z411/trackma#698]
Error Log for trackma-gtk

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/trackma/ui/gtk/imagebox.py", line 44, in run
    self._save_image(self._download_file())
  File "/usr/lib/python3.11/site-packages/trackma/ui/gtk/imagebox.py", line 61, in _save_image
    image.thumbnail((self._width, self._height), Image.ANTIALIAS)
                                                 ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Error Log for trackma-qt

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/trackma/ui/qt/workers.py", line 58, in run
    im.thumbnail((self.size[0], self.size[1]), Image.ANTIALIAS)
                                               ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
[1]    12059 IOT instruction (core dumped)  trackma-qt
```

I have python-pillow installed.
OS : Arch Linux

**Comment by molkoback** [comment]
Fix here: https://github.com/z411/trackma/pull/697

**Comment by uzuto** [comment]
Thanks! replacing image.ANTIALIAS with image.LANCZOS worked but its very slow

**Comment by z411** [comment]
Is it slower? I thought Antialias was an alias for Lanczos. Although now that I think of it Lanczos is probably overkill.

**Comment by molkoback** [comment]
They are the same.
`>>> Image.ANTIALIAS == Image.LANCZOS
True`
