### ISSUE TITLE
I can't access my anime library

### ISSUE THREAD

**Issue by Yukinooooooo** [z411/trackma#723]
I can't access my anime library due to an unknown reason. Usually it works fine except now my [trackma-gtk window](https://rimgo.lunar.icu/IsIPhPx.png) is still displayed like a few days

**Comment by dyskette** [comment]
If you start it from the terminal what messages does it display?

**Comment by Yukinooooooo** [comment]
> If you start it from the terminal what messages does it display?

When I type `trackma-gtk`, it gives the result
```
Trackma GTK v0.8.6
Engine: Trackma v0.8.6 - using account my email (kitsu).
Engine: Reading config files...
Data: Initializing...
libkitsu: Initializing...
Data: Using libkitsu (anime)
Engine: Parsing redirection file...
Engine: Scanning local library...
```

**Comment by dyskette** [comment]
Well, if you are ok with this, you could try clearing the accounts/config and adding them again.

1. Close trackma.
2. Rename the directory `~/.config/trackma` to something else.
3. Open trackma and add the accounts, set your configuration.

That at least should get you out of that state.

**Comment by Yukinooooooo** [comment]
> Well, if you are ok with this, you could try clearing the accounts/config and adding them again.
> 
>     1. Close trackma.
> 
>     2. Rename the directory `~/.config/trackma` to something else.
> 
>     3. Open trackma and add the accounts, set your configuration.
> 
> 
> That at least should get you out of that state.

I followed your advice, it worked wonderfully. I removed my account on `trackma-gtk`, then I deleted the trackma folder located in `~/.config/trackma` then I reopened `trackma-gtk` then added my account, there I have access to my library anime

Thank you very much for the advice and for creating a Trackma application

**Comment by FichteFoll** [comment]
If you still have the old trackma config directory, could you try restoring it temporarily and launching trackma additionally with the `-d` flag to enable debug logging? I'm not convinced that will yield more clues, but it may.

Otherwise we'll need to close the issue since there is nothing we can do to debug this problem without further info.

**Comment by vallx-ny** [comment]
> If you still have the old trackma config directory, could you try restoring it temporarily and launching trackma additionally with the `-d` flag to enable debug logging? I'm not convinced that will yield more clues, but it may.
> 
> Otherwise we'll need to close the issue since there is nothing we can do to debug this problem without further info.

I hope this isn't too much of a necro but, I was having the same issue. 
Renamed old ~./config/trackma to something else, opened the program and it worked.

This is the error I got when opening from the terminal for feedback:

> Traceback (most recent call last):
  File "/usr/bin/trackma", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/trackma/ui/cli.py", line 1068, in main
    main_cmd.start()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/trackma/ui/cli.py", line 180, in start
    self.engine.start()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/trackma/engine.py", line 299, in start
    self.scan_library()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/trackma/engine.py", line 799, in scan_library
    (library, library_cache) = self._add_show_to_library(
                               ~~~~~~~~~~~~~~~~~~~~~~~~~^
        library, library_cache, rescan, fullpath, filename, tracker_list, guess_show)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/trackma/engine.py", line 852, in _add_show_to_library
    anime_info = self.parser_class(self.msg, filename)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'parser_class'

**Comment by FichteFoll** [comment]
@vallx-ny, interesting, I have not seen an error like this before. I strongly suspect this to be a different issue (since we know basically nothing about OP's), so would you mind creating a new issue with that info + your trackma version + your old config file?
