### ISSUE TITLE
Crashing when trying to add OVA

### ISSUE THREAD

**Issue by y0shir** [z411/trackma#725]
Attempting to add OVA to list of currently watched anime crashes both console and qt interface. I use version 0.8.6 from pip.

```
 [mal] (anime) watching >> add "bubblegum crash"
libmal: Searching for bubblegum crash...
Traceback (most recent call last):
  File "/home/USERNAME/.local/bin/trackma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/ui/cli.py", line 1081, in main
    main_cmd.cmdloop()
  File "/usr/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/ui/cli.py", line 777, in onecmd
    return self.execute(cmd, args, line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/ui/cli.py", line 794, in execute
    return func(args)
           ^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/ui/cli.py", line 406, in do_add
    entries = self.engine.search(args[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/engine.py", line 494, in search
    return self.data_handler.search(criteria, method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/data.py", line 218, in search
    results = self.api.search(criteria, method)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/lib/libmal.py", line 333, in search
    results.append(self._parse_info(item['node']))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/trackma/lib/libmal.py", line 380, in _parse_info
    'type': self.type_translate[item['media_type']],
            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'tv_special'
```

**Comment by FichteFoll** [comment]
Closing as it has been addressed by #724.
