### ISSUE TITLE
Trackma-gtk and trackma-qt4 interfaces do not work (I am on void linux)

### ISSUE THREAD

**Issue by P5421135-2** [z411/trackma#731]
When I try to launch these two interfaces these are the errors that I get, I am on void linux if that helps at all.

/usr/lib/python3.12/site-packages/trackma/ui/ 
gtk/window.py:22: PyGIWarning: Gtk was import 
ed without specifying a version first. Use gi 
.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded. 
  from gi.repository import GLib, Gio, Gtk, G 
dk 
Traceback (most recent call last): 
  File "/usr/bin/trackma-gtk", line 33, in <m 
odule> 
    sys.exit(load_entry_point('Trackma==0.8.3 
', 'gui_scripts', 'trackma-gtk')()) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/bin/trackma-gtk", line 25, in im 
portlib_load_entry_point 
    return next(matches).load() 
           ^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.12/importlib/metadat 
a/__init__.py", line 205, in load 
    module = import_module(match.group('modul 
e')) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
^^^^ 
  File "/usr/lib/python3.12/importlib/__init_ 
_.py", line 90, in import_module 
    return _bootstrap._gcd_import(name[level: 
], package, level) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
^^^^^^^^^^^^^^^^^^ 
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import 
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load 
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked 
  File "<frozen importlib._bootstrap_external 
>", line 995, in exec_module 
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/main.py", line 19, in <module> 
    from trackma.ui.gtk.application import Tr 
ackmaApplication 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/application.py", line 18, in <mod 
ule> 
    from trackma.ui.gtk.window import Trackma 
Window 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/window.py", line 25, in <module> 
    from trackma.ui.gtk.accountswindow import 
 AccountsWindow 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/accountswindow.py", line 33, in < 
module> 
    @GtkTemplate(ui=os.path.join(gtk_dir, 'da 
ta/accountswindow.ui')) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/gi_composites.py", line 262, in _ 
_call__ 
    _register_template(cls, template_bytes) 
  File "/usr/lib/python3.12/site-packages/tra 
ckma/ui/gtk/gi_composites.py", line 95, in _r 
egister_template 
    cls.set_connect_func(_connect_func, cls) 
    ^^^^^^^^^^^^^^^^^^^^ 
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func' 
[retr0@DedSec ~]$ trackma-gtk 
/usr/lib/python3.12/site-packages/trackma/ui/gtk/window.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded. 
  from gi.repository import GLib, Gio, Gtk, Gdk 
Traceback (most recent call last): 
  File "/usr/bin/trackma-gtk", line 33, in <module> 
    sys.exit(load_entry_point('Trackma==0.8.3', 'gui_scripts', 'trackma-gtk')()) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/bin/trackma-gtk", line 25, in importlib_load_entry_point 
    return next(matches).load() 
           ^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load 
    module = import_module(match.group('module')) 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module 
    return _bootstrap._gcd_import(name[level:], package, level) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import 
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load 
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked 
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module 
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/main.py", line 19, in <module> 
    from trackma.ui.gtk.application import TrackmaApplication 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/application.py", line 18, in <module> 
    from trackma.ui.gtk.window import TrackmaWindow 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/window.py", line 24, in <module> 
    from trackma.ui.gtk.accountswindow import AccountsWindow 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/accountswindow.py", line 33, in <module> 
    @GtkTemplate(ui=os.path.join(gtk_dir, 'data/accountswindow.ui')) 
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__ 
    _register_template(cls, template_bytes) 
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template 
    cls.set_connect_funootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/main.py", line 19, in <module>
    from trackma.ui.gtk.application import TrackmaApplication
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/application.py", line 18, in <module>
    from trackma.ui.gtk.window import TrackmaWindow
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/window.py", line 24, in <module>
    from trackma.ui.gtk.accountswindow import AccountsWindow
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/accountswindow.py", line 33, in <module>
    @GtkTemplate(ui=os.path.join(gtk_dir, 'data/accountswindow.ui'))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__
    _register_template(cls, template_bytes)
  File "/usr/lib/python3.12/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template
    cls.set_connect_func(_connect_func, cls)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func'
c(_connect_func, cls) 
    ^^^^^^^^^^^^^^^^^^^^ 
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func' 

Trackma-qt v0.8.3
Traceback (most recent call last):
  File "/usr/bin/trackma-qt4", line 33, in <module>
    sys.exit(load_entry_point('Trackma==0.8.3', 'gui_scripts', 'trackma-qt4')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/trackma-qt4", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 207, in load
    return functools.reduce(getattr, attrs, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'trackma.ui.qt.qt4ui' has no attribute 'main'

**Comment by ahmubashshir** [comment]
Update your trackma, or remove gtk4, trackma-gtk will start working, and you should not be using -qt4, it's EOL

**Comment by P5421135-2** [comment]
> Update your trackma, or remove gtk4, trackma-gtk will start working, and you should not be using -qt4, it's EOL

Thanks for the quick response the gtk version is working now.
